# Generated by Django 5.0.1 on 2025-08-14 13:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('taskdoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='MEDIUM', max_length=20),
        ),
    ]
