# Generated by Django 5.0.1 on 2025-08-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskdoor', '0003_alter_task_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='titre',
        ),
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archivée'),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('LOW', 'L'), ('MEDIUM', 'M'), ('HIGH', 'H')], default='MEDIUM', max_length=20, verbose_name='Importance'),
        ),
    ]
